### ISSUE TITLE
EFI for MacOs 13 Ventura

### ISSUE THREAD

**Issue by 0xgobag** [Human7900/macOS-HP-Probook-430-G3-Resources#11]
Hi dude, please make efi for mac os ventura

**Comment by Baio1977** [comment]
[EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/8886387/EFI.zip)

Test this EFI , if start ioreg

**Comment by Human79** [comment]
Greetings!
I will make one however I have been extremely busy so it will take some time.
Thank you for your patience!
Regards
-Human7900

**Comment by Human79** [comment]
Coming up tomorrow!

**Comment by 0xgobag** [comment]
I waiting for it.. thanks dude

**Comment by Human79** [comment]
Thanks @dekill93 and @Baio1977 for your patience!
The release is out now. If you face any issue, feel free to create a new issue.
Regards
~Human7900.
