### ISSUE TITLE
BOOTLOOP using latest EFI and ventura

### ISSUE THREAD

**Issue by fandofastest** [Human7900/macOS-HP-Probook-430-G3-Resources#16]
BOOTLOOP using latest EFI and ventura

**Comment by Human79** [comment]
Hi @fandofastest ,
will update the repo within this week. Thanks for your patience!

**Comment by Human79** [comment]
Hi @fandofastest, please try the latest release!

**Comment by fandofastest** [comment]
has fix bro, 
note  : 
1.  dont forget to setting VRAM to 128Mb in BIOS -> this my mistake
2.  u can use intel wifi  kext on installation , but when start to main OS this will make BOOTLOOP,
 solution, disable wifi from bios, install Heliport , enable again from BIOS -> problem fix, wifi can use normally
 
 thanks

**Comment by Human79** [comment]
Glad to see the issue is resolved!
~Human7900.
