### ISSUE TITLE
EFI Issues (See for details)

### ISSUE THREAD

**Issue by mikailreialt** [Human7900/macOS-HP-Probook-430-G3-Resources#17]
Intel wifi ac 8260 is working on mac os big sur installer using itlwm
note: but you have to edit the Info.plist ssid and password to get connected. (CASE SENSITIVE)

**Comment by mikailreialt** [comment]
i think you should add that..

**Comment by Human79** [comment]
Hey there,
I think it is known that intel wifi works with itwlm, I think there is no need to add that. You could even use airportitwlm in your case.

**Comment by mikailreialt** [comment]
yeah, but why is that still listed for not working???

**Comment by mikailreialt** [comment]
and why the hackintool detected that im still using oc 0.9.2 even though i installed 0.9.3 from your release @Human79

**Comment by Human79** [comment]
My unit came with a Realtek wifi card, that's why it's listed as not-working. You're right, I'll generalise the information regarding wifi in the ReadMe!

The Hackintool issue can be resolved by resetting the NVRAM. You can try and let me know! @mikailreialt 
~Human79.

**Comment by mikailreialt** [comment]
i will try though, btw any fix for the usb next to HDMI??

**Comment by Human79** [comment]
Yes, remove my USBMap.kext and map your usb ports on your own! My port is damaged so i disabled it!

**Comment by mikailreialt** [comment]
if i delete it do i have to update the config .plist? and do i can still use the usb while it's deleted??

**Comment by mikailreialt** [comment]
> My unit came with a Realtek wifi card, that's why it's listed as not-working. You're right, I'll generalise the information regarding wifi in the ReadMe!
> 
> The Hackintool issue can be resolved by resetting the NVRAM. You can try and let me know! @mikailreialt ~Human79.

my unit comes in intel and it works!

**Comment by Human79** [comment]
> if i delete it do i have to update the config .plist? and do i can still use the usb while it's deleted??

You'll have to delete my .kext and follow the USBMap guide (which requires using a dummy USBMap.kext to add and then reboot to map your USB ports) and Yes, you'll have to update the config.plist.

Please follow this guide : https://github.com/corpnewt/USBMap

or this : https://www.reddit.com/r/hackintosh/comments/ta1ef4/guide_easy_usb_mapping_with_usbtoolbox_on_windows/

**Comment by Human79** [comment]
> > My unit came with a Realtek wifi card, that's why it's listed as not-working. You're right, I'll generalise the information regarding wifi in the ReadMe!
> > The Hackintool issue can be resolved by resetting the NVRAM. You can try and let me know! @mikailreialt ~Human79.
> 
> my unit comes in intel and it works!

Will update the ReadMe soon.

**Comment by mikailreialt** [comment]
> > if i delete it do i have to update the config .plist? and do i can still use the usb while it's deleted??
> 
> You'll have to delete my .kext and follow the USBMap guide (which requires using a dummy USBMap.kext to add and then reboot to map your USB ports) and Yes, you'll have to update the config.plist.
> 
> Please follow this guide : https://github.com/corpnewt/USBMap
> 
> or this : https://www.reddit.com/r/hackintosh/comments/ta1ef4/guide_easy_usb_mapping_with_usbtoolbox_on_windows/

can i get the dummy??

**Comment by Human79** [comment]
> > > if i delete it do i have to update the config .plist? and do i can still use the usb while it's deleted??
> > 
> > 
> > You'll have to delete my .kext and follow the USBMap guide (which requires using a dummy USBMap.kext to add and then reboot to map your USB ports) and Yes, you'll have to update the config.plist.
> > Please follow this guide : https://github.com/corpnewt/USBMap
> > or this : https://www.reddit.com/r/hackintosh/comments/ta1ef4/guide_easy_usb_mapping_with_usbtoolbox_on_windows/
> 
> can i get the dummy??

You can create that using USBMap!

**Comment by mikailreialt** [comment]
> > > > if i delete it do i have to update the config .plist? and do i can still use the usb while it's deleted??
> > > 
> > > 
> > > You'll have to delete my .kext and follow the USBMap guide (which requires using a dummy USBMap.kext to add and then reboot to map your USB ports) and Yes, you'll have to update the config.plist.
> > > Please follow this guide : https://github.com/corpnewt/USBMap
> > > or this : https://www.reddit.com/r/hackintosh/comments/ta1ef4/guide_easy_usb_mapping_with_usbtoolbox_on_windows/
> > 
> > 
> > can i get the dummy??
> 
> You can create that using USBMap!

i dont have the mac os rn..

**Comment by Human79** [comment]
You can use the second guide I mentioned to create it on Windows!

**Comment by mikailreialt** [comment]
i recently do this it stuck on mac os logo though, will info you later again

**Comment by Human79** [comment]
Sure thing! Reopening this issue.

**Comment by mikailreialt** [comment]
hey, so i tried it stuck on apple logo and then restart

**Comment by mikailreialt** [comment]
i choose on the OC is mac os installer not the usb itself

**Comment by mikailreialt** [comment]
will try re download the base system will info you again @Human79

**Comment by mikailreialt** [comment]
Welp, it doesn't work. any solution? @Human79 ?

**Comment by Human79** [comment]
Please boot with the -v boot-arg and send me a pic where it stalls.

**Comment by mikailreialt** [comment]
hello, are you online rn??

**Comment by Human79** [comment]
Please post your isssues here, I’ll look at them when I’m free.

**Comment by mikailreialt** [comment]
Hey bro, i think the problem is fixed now, but now the last problem is, the efi partition on my hdd, i wanna extend it, any solution?

**Comment by mikailreialt** [comment]
I cannot put the airportlwm ventura because of that

**Comment by Human79** [comment]
Unfortunately you'll have to backup and delete your EFI partition and create a new (larger) one.

**Comment by mikailreialt** [comment]
Welp but how, to do that?

**Comment by Human79** [comment]
You can use Minitool Partiton Wizard (free) on windows or google it!

**Comment by mikailreialt** [comment]
You know the tutorial?

Pada tanggal Sab, 1 Jul 2023 02.51, A Human ***@***.***>
menulis:

**Comment by Human79** [comment]
https://www.diskpart.com/windows-11/windows-11-efi-patition-size-1503.amp.html

**Comment by mikailreialt** [comment]
Do i have must delete my windows installation? I Guess so..

**Comment by Human79** [comment]
@mikailreialt Nope.

**Comment by mikailreialt** [comment]
Huh, what... I saw the tutorial it must have a unallocated space on drive which mine isn't, also my Windows Drive on the first partition (if you know what i mean) that is impossible though.. unless i delete that partition

**Comment by Human79** [comment]
Shrink your windows partition to get some unallocated space and make that your EFI partition.

**Comment by mikailreialt** [comment]
But it goes to the right not left????

**Comment by Human79** [comment]
Not necessarily if you use Minitool.

**Comment by mikailreialt** [comment]
Ok then i will close this as done, thanks a lot for the help!
