### ISSUE TITLE
OC is detected as 0.9.2

### ISSUE THREAD

**Issue by mikailreialt** [Human7900/macOS-HP-Probook-430-G3-Resources#20]
hi @Human79 thanks a lot from your help in the previous issue, now my issue is why in the hackintool is detected as OC 0.9.2 even though I installed OC 0.9.3 from your release... any help or solution

**Comment by mikailreialt** [comment]
![Screenshot 2023-07-02 at 06 31 41](https://github.com/Human79/macOS-HP-Probook-430-G3-Resources/assets/135125031/50687a32-cfe6-4607-834d-2eb5182353fa)

**Comment by Human79** [comment]
Please try to reset NVRAM.

**Comment by mikailreialt** [comment]
already it's still see OC 0.9.2

**Comment by Human79** [comment]
Please reset NVRAM and try this EFI @mikailreialt .
[EFI 4.zip](https://github.com/Human79/macOS-HP-Probook-430-G3-Resources/files/11939930/EFI.4.zip)

**Comment by mikailreialt** [comment]
late response, yeah that fixed the problem THANKS A LOT @Human79 !
