### ISSUE TITLE
RTS522a card reader

### ISSUE THREAD

**Issue by ghost** [Human7900/macOS-HP-Probook-430-G3-Resources#3]
Hello. 
I don’t know the card reader works for your efi but i have solution for RTS522a. 
tested on my  Hp elitebook 840 g3(similar laptop with your)
Sinetek /Cholonam for Sinetek-rtsx (SD Card reader)
https://github.com/cholonam/Sinetek-rtsx
you have an interesting solution I'll try to take something for myself.

**Comment by Human79** [comment]
Hi,
Sorry for replying late. I have got the Realtek SD card reader working working and also shown in system information in card readers. It will be included in this repo soon.
![Screen Shot 2021-07-01 at 12 19 45 PM](https://user-images.githubusercontent.com/84245065/124079364-a550fe00-da66-11eb-9cbb-f9aa3f61068f.png) Though the fans are not shown in iStatMenus.

**Comment by Human79** [comment]
Should be fixed in latest release. Please test and report back.

**Comment by Human79** [comment]
Will close the issue if you not respond.
EDIT: This issue will be reopened once you respond.
