### ISSUE TITLE
One USB 3.0 Doesn't work for me

### ISSUE THREAD

**Issue by pseter17** [Human7900/macOS-HP-Probook-430-G3-Resources#6]
Hi,

I successfully installed macOS Big Sur with yours EFI Folder, but one usb 3.0, doesn't work, usb not showing any activity, macOS doesn't see usb drive, it's port on right side, near fingerprint sensor. Any ideas? Thanks for answer.

**Comment by Human79** [comment]
Hi @pseter17,
You can create your own USB Map kext and report back.
Regards.
~Human7900.

**Comment by pseter17** [comment]
In usb map kext i only see two usb ports too :/ and SD card reader doesnt work for me too, Wifi is fully working with this
https://github.com/OpenIntelWireless/itlwm 

And Can you try to update OpenCore to newest version? Thanks

**Comment by Human79** [comment]
Is the SD Card Reader showing up in System Preferences?
OpenCore 0.7.2 will be released tomorrow.
Don't use my USBMap kext while mapping your own.
Also, can you get a pic of the port you're trying to fix?
Does it work in Windows?

**Comment by pseter17** [comment]
![Snímka obrazovky 2021-08-08 o 22 15 44](https://user-images.githubusercontent.com/67827161/128644536-4819d7d6-4b93-44fe-a05f-3bafff62f75e.png)

I see this in System Preferences, port does work in windows, its port on right side, 2nd from HDMI Port

**Comment by pseter17** [comment]
USB port is working after changing USBMap kext to new, mine, but SD Card Reader doesn't work, sleep mode doesn't work too, and I can't turn off bluetooth. Thanks for help.

**Comment by pseter17** [comment]
You tried repair powerchime by this?

https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-boot-chime-with-audiodxe

**Comment by Human79** [comment]
> You tried repair powerchime by this?
> 
> https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-boot-chime-with-audiodxe

That is for the Boot Chime.

**Comment by Human79** [comment]
Can you try this EFI for SD Card Reader?
It will not show up in System Report but it should work.
For the sleep, please re-check the Bios settings.
Also, I have updated OpenCore to the latest version.
Regards.
~Human7900.
[EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/6954725/EFI.zip)

**Comment by Human79** [comment]
Please reply if you wish to keep this issue open.
EDIT: I am closing this issue, it will be reopened if you wish.
