### ISSUE TITLE
SD Card Reader and everything works, but HDMI Audio not.

### ISSUE THREAD

**Issue by benjenq** [Human7900/macOS-HP-Probook-430-G3-Resources#7]
I changed wifi adapter to BCM94360CD for my 430 G3 laptop and hackintosh Big Sur with this EFI files yesterday. Almost everything works perfect  except Intel HDMI Audio (No HDMI Audio output when HDMI video output working ) . Will you implement this function ?

**Comment by Human79** [comment]
Hey,
I would love to implement this but at the moment I do not have any HDMI cable to test.
If you can help me in testing, it would be great!
Regards.
~Human7900.

**Comment by benjenq** [comment]
Hi Human7900:

I've solved Intel HDMI Audio issue from your EFI file "OpenCore 0.7.2 (1.0.4)".

Just add 4 key-value in DeviceProperties->Add->PciRoot(0x0)/Pci(0x2,0x0) as following:
```
			<key>framebuffer-con1-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-has-lspcon</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-preferred-lspcon-mode</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-type</key>
			<data>AAgAAA==</data>
```
Full Properties for PciRoot(0x0)/Pci(0x2,0x0)
```
		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
		<dict>
			<key>AAPL,ig-platform-id</key>
			<data>AAAWGQ==</data>
			<key>enable-hdmi20</key>
			<data>AQAAAA==</data>
			<key>framebuffer-fbmem</key>
			<data>AACQAA==</data>
			<key>framebuffer-patch-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-stolenmem</key>
			<data>AAAwAQ==</data>
			<key>framebuffer-unifiedmem</key>
			<data>AAAAgA==</data>
			<key>hda-gfx</key>
			<data>AAsKAA==</data>
			<key>framebuffer-con1-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-has-lspcon</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-preferred-lspcon-mode</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-type</key>
			<data>AAgAAA==</data>
		</dict>
```
Intel HDMI Audio return to works on my HP Probook 430 G3 (i5-6200U)

**Comment by Human79** [comment]
Thanks for your work!
Good to know it works. I will look into integrating into my Opencore 0.7.3 release.
Also, thanks for testing HDMI, I will update the Readme as well.
Thanks again,
~Human7900
