### ISSUE TITLE
cannot boot from latest efi

### ISSUE THREAD

**Issue by robi62** [Human7900/macOS-HP-Probook-430-G3-Resources#8]
Hi what a great work I can boot now from OpenCore to windows
Latest efi doesn't work nothing happens just a blank screen Previous version efi does but no fans speed or any sensors showing I know I need to remap usb but overall great job

**Comment by robi62** [comment]
I have 3 laptops all hp 430g3 all latest bios but cannot boot from your latest efi.
Any ideas why????
Also Im experimenting with your ssdt as I m trying to get sensors with fakesmc I can but when I boot to window it tells me battery is low and even when I put charger in not detected ????

**Comment by Human79** [comment]
Please  give me time till Monday and I’ll get back to you.
Thank you for your patience.

**Comment by robi62** [comment]
Hi no problems I have been experimenting to try to get fakesmc working I get 2 results 1 working fan but no battery 2 no fan but yes battery I don't know how to extract fan ssdt from my dssdt Maybe you can point me in the right direction
Just tested on efi72 card reader works hdmi no audio working There is no output for cdmi sound in system sound settings

**Comment by Human79** [comment]
Please try the latest release.

**Comment by robi62** [comment]
I can't boot from this either no Idea why Up to op 072 I can after that doesn't boot

**Comment by Human79** [comment]
What is the error you are facing?

**Comment by robi62** [comment]
It does not do anything ....
When I press boot from opencore. Efi nothing doesn’t carry on
The only thing I can check if my settings in bios are different from yours but never had a problem in booting with different oc efi or clover before

**Comment by robi62** [comment]
bios settings same as yours but still not booting

**Comment by robi62** [comment]
I managed to boot If I add drivers from oc config as you had none enabled
You can see fans but fan quiet patch from Rehabman doesn't work It also boot without the theme no idea why

**Comment by robi62** [comment]
no joy If I boot from your refi latest 2 untouched nothing happens Can you tell me where device smcd = fan is on this ssdt??
[SSDT-4x0-G3-Skylake.aml.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/7323901/SSDT-4x0-G3-Skylake.aml.zip)
?

**Comment by robi62** [comment]
I  have no idea why my 430 g3 cannot boot from you last 2 efis If you feel I m a bit too annoying you can close the issue
It is not my intention to stress you Have a good day

**Comment by robi62** [comment]
I managed to Fix HDMI sound  thanks to OSx latitude add this to device
framebuffer-con1-enable 1 NUMBER
framebuffer-con1-type 00080000 DATA

**Comment by robi62** [comment]
I have sorted all the problems I m using this GitHub which have been ported from yours
https://github.com/Baio1977/HP-Probook-430-G3-Skylake
