### ISSUE TITLE
How can I get rid of sleep issues?

### ISSUE THREAD

**Issue by techmeav** [Human7900/macOS-HP-Probook-430-G3-Resources#9]
Hi
It's been a long time since I last talked to u.
Hope ur doin fine.

So, i just got Monterey working on same specs as urs but the following differ : 
- iGPU is 1566 MB
- Audio is realtek (i have this working)
- Ethernet is RTL8100 (It keeps on connecting and disconnecting after a regular interval.)
- I am on HP Pavillion
- Resolution is 1920x1080 (FHD)

I can share you my efi if u want via Google Drive

**Comment by Human79** [comment]
Hi there!
I would need to see your EFI before I can comment on anything.
Regards
-Human7900

**Comment by Human79** [comment]
Closing this issue due to non activity.
